server:
  port: 8080

spring:
  application:
    name: SpringAiAlibaba
  ai:
    openai:
      chat:
        base-url: https://open.bigmodel.cn/api/paas/v4/
        api-key: 9f6a702c511542ec8acefd50b3ba0db1.AOqEKx1gpr1acK46

