server:
  port: 8081
  servlet:
    encoding:
      charset: UTF-8
      force: true
spring:
  profiles:
    active: local
  ai:
    zhipuai:
      api-key: <your-api-key>
      base-url: https://open.bigmodel.cn/api/paas/
      chat:
        options:
          model: glm-4.5-flash
    dashscope:
      api-key: <anything>
    chat:
      client:
        enabled: false # 默认关闭
logging:
  level:
    org.springframework.ai.chat.client.advisor: debug


