server:
  port: 8081
  servlet:
    encoding:
      charset: UTF-8
      force: true
spring:
  profiles:
    active: local
  datasource:
    url: jdbc:postgresql://localhost:5432/ssa
    username: root
    password: <your password>
    driver-class-name: org.postgresql.Driver
  ai:
    zhipuai:
      api-key: <your-api-key>
      base-url: https://open.bigmodel.cn/api/paas/
      chat:
        options:
          model: glm-4.5-flash
    dashscope:
      api-key: <anything>
    chat:
      client:
        enabled: false # 默认关闭
      memory:
        repository:
          jdbc:
            initialize-schema: always # 自动创建表

logging:
  level:
    org.springframework.ai.chat.client.advisor: debug


