server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true

spring:
  application:
    name: SpringAiAlibaba
  ai:
    zhipuai:
      api-key: <your-api-key>
      base-url: https://open.bigmodel.cn/api/paas/
      chat:
        options:
          model: glm-4.5-flash

    dashscope:
      api-key: <anything>


